#!/usr/bin/env bash

aws ecr get-login-password --region us-east-1 | podman login --username AWS --password-stdin 993874376304.dkr.ecr.us-east-1.amazonaws.com/streamline-puller
podman manifest push --all streamline-puller:latest 993874376304.dkr.ecr.us-east-1.amazonaws.com/streamline-puller:latest
